[package]
name = "ccwc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytecount = "0.6.7"
clap = { version = "4.4.12", features = ["derive"] }
tempfile = "3.9.0"
